import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'

export default function Home() {
  const songs = [{ phrase: "“Qual o mistério que te move?”", name: "misterios.mp3", image: "/akira.gif", sound: "../audio/misterios.mp3", artist: "Alquimista" },
  { phrase: "“O parachoque de uma moto é seu peito meu nobre”", name: "hayabusa.mp3", image: "/hayabusa.gif", sound: "../audio/hayabusa.mp3", artist: "Alquimista" },
  { phrase: "“Os limites entre o real e o virtual não foram definidos”", name: "Dia_Chuvoso.mp3", image: "/lain.gif", sound: "../audio/Dia_Chuvoso.mp3", artist: "Alquimista" },
  { phrase: "“A cada kill de canalha eu digo: Você nunca vai ficar velho.”", name: "Fim_de_Semana.mp3", image: "/tiros.gif", sound: "../audio/Fim_de_Semana.mp3", artist: "Alquimista e TedBeats" },
  ]
  return (
    <>
      <Head>
        <title>Álbu!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5 bg-gray-900" >
        <div className="bg-purple-900 p-3 rounded-xl text-center">
          <h1 className="font-medium text-white">Welcome 2023 ?</h1>
        </div>
        {songs.map((value, index) => {
          return <div key={index} className="mt-5">
            <Card artist={value.artist} phrase={value.phrase} name={value.name} image={value.image} sound={value.sound} />
          </div>
        })}
      </main>
    </>
  )
}
